pipelines:
  - name: bindu11
    steps:
      - name: test_11
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions: 
#                   - 8.16.0
              custom:
                name: drydock/u16node
                tag: master
        execution:
          onExecute:
            - printenv
