resources:
  - name: bash
    type: gitRepo
    repoPath: vijayreddy1991/resources
    configuration:
      integrationName: vijayku_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline1234
    steps:
      - name: testbash1
        type: bash
        configuration:
          affinityGroup: vijay@#$%^&*
          nodePool: kermit_ubuntu_pool
          chronological: true        
        setup:
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 8.16.0
              custom:
                name: drydock/c7node
                tag: master
                options: ""
        triggeredBy:
          resources:
            - bash
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - echo "vijay"

      - name: testbash2
        type: bash
        configuration:
          affinityGroup: vijay@#$%^&*
          priority: 2
          nodePool: kermit_ubuntu_pool
          chronological: true
        setup:
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 10.15.3
              custom:
                name: drydock/u16node
                tag: master
                options: ""
        triggeredBy:
          steps:
            - testbash1
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - echo "vijay"
            

      - name: testbash3
        type: bash
        configuration:
          affinityGroup: vijay@#$%^&*
          priority: 1
          nodePool: kermit_ubuntu_pool
          chronological: true        
        setup: 
          runtime:            
            type: image
            image:
              auto:
                language: nodejs
                versions: 
                  - 8.16.0
              custom:
                name: drydock/u16node
                tag: master
                options: ""
        triggeredBy:
          steps:
            - testbash2
        execution:
          onStart:
            - printenv
          onExecute:
            - printenv
            - echo "vijay"

