pipelines:
  - name: bindu11
    steps:
      - name: test_11
        type: Bash
        configuration:
          runtime:       
            type: image
              custom:
                name: drydock/u16nodejs
                tag: master
        execution:
          onExecute:
            - printenv
